In [3]:
import torch
print(torch.__version__)

2.7.1+cu118


In [4]:
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("CUDA is available!")
    print("GPU Device Name:", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print("CUDA is not available, using CPU instead.")

# Create a random tensor and move it to GPU
x = torch.randn(3, 3).to(device)
y = torch.randn(3, 3).to(device)

# Perform a simple operation
z = x + y

print("Tensor x:\n", x)
print("Tensor y:\n", y)
print("x + y =\n", z)

# Check current device
print("Current device:", z.device)


CUDA is available!
GPU Device Name: NVIDIA GeForce RTX 3060
Tensor x:
 tensor([[ 0.2775, -2.1411,  0.2302],
        [ 1.3265, -0.3509,  1.3754],
        [-0.3426,  1.6515, -0.2335]], device='cuda:0')
Tensor y:
 tensor([[-0.4109, -0.5895, -3.0762],
        [-0.2012, -0.3372,  2.2333],
        [-0.2090, -1.2054,  0.1745]], device='cuda:0')
x + y =
 tensor([[-0.1334, -2.7306, -2.8460],
        [ 1.1253, -0.6881,  3.6088],
        [-0.5516,  0.4461, -0.0590]], device='cuda:0')
Current device: cuda:0
